version: 0.0  
os: linux  
files:  
  - source: /  
    destination: /app/frontend/front
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/clean_dir.sh  
      timeout: 300  
  ApplicationStart:  
    - location: scripts/start_server.sh  
      timeout: 300
